### ISSUE TITLE
Map box right border is misaligned

### ISSUE THREAD

**Issue by Dawnflash** [MI-AFP/hw06#4]
In `src/MapTraveler.hs:88-89` the right border doesn't align correctly due to using `replicate (w-2)` instead of `replicate w`, which is the correct number of `═` to print to cover the map's width since the box is 2 chars wider than the map.

**Comment by MarekSuchanek** [comment]
Fixed in https://github.com/MI-AFP/hw06/commit/78f8feaf42c1a8a02d21528c8cd7c0e9c0c1ee74
